# Training constants
MAX_MEM = 100_000
BATCH_SIZE = 2**6
LEARN_RATE = 0.01

# Game state indices
BET_HIST_IDX = 0
PLAYER_CT_IDX = 1
LAST_ACTION_IDX = 2
TOTAL_DICE_IDX = 3
HIDDEN_DICE_START_IDX = 4

# Game constants
MAX_DICE_PER_PLAYER = 5
MAX_FACE_VALUE = 6
MIN_FACE_VALUE = 1
MIN_PLAYERS = 2

#LIE_TUPLE = (-1,-1)
LAST_BID_IDX = -2

# State approximation constants
NUM_CLUSTERS = 100
MAX_HISTORY_LENGTH = 10

# Approximation constants
QTY_DISTANCE_WEIGHT = 0.4
FACE_DISTANCE_WEIGHT = 0.3
QTY_RATIO_DISTANCE_WEIGHT = 0.2
HISTORY_LENGTH_DISTANCE_WEIGHT = 0.1
